workflows:
  # Android Only - Tối ưu cho gói Free
  android-free:
    name: Android Free Build
    max_build_duration: 45  # Giới hạn 45 phút để tránh build kéo dài
    instance_type: mac_mini_m1
    triggering:
      events:
        - tag  # Chỉ build khi tạo tag (release)
      tag_patterns:
        - pattern: 'v*'
          include: true
      cancel_previous_builds: true  # Hủy build cũ nếu có build mới
    
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.fidobox.kdtd"
        GOOGLE_PLAY_TRACK: internal
      flutter: stable
    
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/.gradle/caches
        - $HOME/.gradle/wrapper
        - $HOME/Library/Caches/CocoaPods
    
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Build AAB (Release only)
        script: |
          flutter build appbundle --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
    
    publishing:
      email:
        recipients:
          - dev@fidobox.com
        notify:
          success: true
          failure: true
      
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true

  # iOS Only - Tối ưu cho gói Free
  ios-free:
    name: iOS Free Build
    max_build_duration: 45
    instance_type: mac_mini_m1
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*'
          include: true
      cancel_previous_builds: true
    
    integrations:
      app_store_connect: codemagic
    
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.fidobox.kdtd
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.fidobox.kdtd"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/Library/Caches/CocoaPods
    
    scripts:
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      
      - name: Get Flutter packages
        script: |
          flutter pub get
      
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      
      - name: Build IPA
        script: |
          flutter build ipa --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      email:
        recipients:
          - dev@fidobox.com
        notify:
          success: true
          failure: true
      
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers

  # Quick Test - Chỉ chạy test, không build
  quick-test:
    name: Quick Test
    max_build_duration: 15
    instance_type: mac_mini_m1
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
      cancel_previous_builds: true
    
    environment:
      flutter: stable
    
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
    
    scripts:
      - name: Get packages
        script: flutter pub get
      
      - name: Analyze
        script: flutter analyze
        ignore_failure: true
      
      - name: Run tests
        script: flutter test
        ignore_failure: true
    
    publishing:
      email:
        recipients:
          - dev@fidobox.com
        notify:
          failure: true  # Chỉ thông báo khi fail
