workflows:
  # Android Build Workflow
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
        - pattern: 'develop'
          include: true
          source: true
      tag_patterns:
        - pattern: 'v*'
          include: true
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.fidobox.kdtd"
        GOOGLE_PLAY_TRACK: internal
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Flutter analyze
        script: |
          flutter analyze
      
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      
      - name: Build APK (Debug)
        script: |
          flutter build apk --debug
      
      - name: Build AAB (Release)
        script: |
          flutter build appbundle --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    
    publishing:
      email:
        recipients:
          - dev@fidobox.com
        notify:
          success: true
          failure: true
      
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true

  # iOS Build Workflow
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
        - pattern: 'develop'
          include: true
          source: true
      tag_patterns:
        - pattern: 'v*'
          include: true
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.fidobox.kdtd
      groups:
        - app_store_credentials
      vars:
        APP_STORE_APPLE_ID: 1234567890
        BUNDLE_ID: "com.fidobox.kdtd"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      
      - name: Flutter analyze
        script: |
          flutter analyze
      
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      
      - name: Build ipa for distribution
        script: |
          flutter build ipa --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    
    publishing:
      email:
        recipients:
          - dev@fidobox.com
        notify:
          success: true
          failure: true
      
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
        submit_to_app_store: false

  # Development Build (Both platforms)
  dev-build:
    name: Development Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'develop'
          include: true
          source: true
        - pattern: 'feature/*'
          include: true
          source: true
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Flutter analyze
        script: |
          flutter analyze
        ignore_failure: true
      
      - name: Build Android APK
        script: |
          flutter build apk --debug
      
      - name: Build iOS (no signing)
        script: |
          flutter build ios --debug --no-codesign
    
    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/iphoneos/*.app
    
    publishing:
      email:
        recipients:
          - dev@fidobox.com
        notify:
          success: true
          failure: true
